name: Scrape Loterías RD
on:
  schedule:
    - cron: "*/30 * * * *"   # cada 30 min (UTC)
  workflow_dispatch: {}      # botón "Run workflow"
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: python scraper/main.py
      - name: Commit & push
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add public/
            git commit -m "chore: resultados $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          else
            echo "Sin cambios."
          fi
