name: Scrape Loterías RD

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: {}

concurrency:
  group: scrape-loterias-rd
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0        # <-- necesario para poder rebase/pull

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python -m scraper.main   # ejecutar como módulo

      - name: Commit & push
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          if [[ -n "$(git status --porcelain public/)" ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add public/
            git commit -m "chore: resultados $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            # integra cambios remotos y luego empuja
            git fetch origin "$BRANCH_NAME"
            git pull --rebase origin "$BRANCH_NAME"
            git push origin HEAD:"$BRANCH_NAME"
          else
            echo "Sin cambios."
          fi
